#
# Default Log Level is info
#
log4cplus.rootLogger=trace, console, logfile

####################################
# Special categories Log Level Control
# Note: logger and additivity should appear in pairs to avoid duplicated message
#
# log4cplus.logger.svc=error, console, logfile
# log4cplus.additivity.svc=false

#log4cplus.logger.framework=error, console, logfile
#log4cplus.additivity.framework=false

# log4cplus.logger.syslib=info, console, logfile
# log4cplus.additivity.syslib=false


#
# Logging to Console
#
log4cplus.appender.console=log4cplus::ConsoleAppender
log4cplus.appender.console.layout=log4cplus::PatternLayout
log4cplus.appender.console.layout.ConversionPattern=%t %D{%Y-%m-%dT%T.%q}Z %5p %c.%L: %m %n

#
# Logging to logfile
#
log4cplus.appender.logfile=log4cplus::RollingFileAppender
log4cplus.appender.logfile.MaxFileSize=6000KB
log4cplus.appender.logfile.MaxBackupIndex=50
log4cplus.appender.logfile.File=./trading.log
log4cplus.appender.logfile.layout=log4cplus::PatternLayout
log4cplus.appender.logfile.layout.ConversionPattern=%t %D{%Y-%m-%dT%T.%q}Z %5p %c.%L: %m %n


#
# Logging to eventfile
#
# log4cplus.appender.eventfile=log4cplus::RollingFileAppender
# log4cplus.appender.eventfile.MaxFileSize=6000KB
# log4cplus.appender.eventfile.MaxBackupIndex=10
# log4cplus.appender.eventfile.File=../log/event.log
# log4cplus.appender.eventfile.layout=log4cplus::PatternLayout
# log4cplus.appender.eventfile.layout.ConversionPattern=%t %D{%Y-%m-%dT%T.%q}Z %5p %c.%L: %m %n